# Generated by Django 3.2 on 2021-06-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tages',
            new_name='tags',
        ),
    ]
